FROM alpine:latest
MAINTAINER "Carter Mbotho <carter@suilteam.com>"

# Install dependencies
RUN apk  add --update --no-cache libressl libstdc++ libpq libuuid sqlite-libs

# Copy Binaries
COPY artifacts/ /usr/