---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dc.
--- DateTime: 2020-02-29 1:39 p.m.
---

local Example = Fixture('BasicTestFixture', "A basic test feature used as an example")

Example("ExampleTestPass", "Example test case passing")
:run(function(ctx)
    Test(true, "Example passing test case")
end)

Example("ExampleTestEllapsed", "Test ellapsed time using test context")
:before(function(ctx)
    ctx.start = Swept:now()
end)
:run(function(ctx)
    Swept:sleep(2000)
    Test((Swept:now()-ctx.start) >= 2000, "Ellapsed time should be greator or equal to 2 seconds")
end)
:after(function(ctx)
    ctx("after", "test done {start  %d, end %d}", ctx.start, Swept:now())
end)

Example("ExampleTestSkipped", "This test case should be skipped")
        :run(function(ctx)
    Test(false, "Test case shouldn't be run, it is disabled")
end)
:disable("Disabling test case to demonstrate disabled test cases")

return Example