---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dc.
--- DateTime: 2020-02-29 1:39 p.m.
---

local Example = Fixture()
Example("ExampleTestPass", "Example test case passing")
:run(function(ctx)
    Test(true, "Example passing test case")
end)

Example("ExampleTestEllapsed", "Test ellapsed time using test context")
:before(function(ctx)
    ctx.start = Swept:now()
end)
:run(function(ctx)
    Swept:sleep(2000)
    Test((Swept:now()-ctx.start) >= 2000, "Ellapsed time should be greator or equal to 2 seconds")
end)
:after(function(ctx)
    ctx.reporter:success("after", "test done {start  %d, end %d}", ctx.start, Swept:now())
end)

return Example